---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-index
spec:
  params:
    - name: bundle_image
  workspaces:
    - name: output
  steps:
    - name: generate
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.output.path)
      script: |
        #! /usr/bin/env bash
        set -xe

        curl -L -o /bin/opm https://github.com/operator-framework/operator-registry/releases/download/v1.17.1/linux-amd64-opm
        chmod +x /bin/opm
        # TODO should --from-index be specified?
        # --permissive is used to overcome errors about the missing bundles
        # this one replaces.
        opm index add \
          --bundles $(params.bundle_image) \
          --container-tool none \
          --out-dockerfile Dockerfile \
          --generate \
          --skip-tls \
          --permissive

        ls -alhR
