---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: operator-test-pipeline
spec:
  params:
    - name: git_repo_url
    - name: git_revision
    - name: bundle_path
    - name: registry
      default: default-route-openshift-image-registry.apps-crc.testing
  workspaces:
    - name: pipeline
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git_repo_url)
        - name: revision
          value: $(params.git_revision)
      workspaces:
        - name: output
          workspace: pipeline
          subPath: src

    - name: validate
      runAfter:
        - checkout
      taskRef:
        name: operator-cert-validate
      params:
        - name: bundle_path
          value: "$(params.bundle_path)"
      workspaces:
        - name: source
          workspace: pipeline
          subPath: src

    - name: build-bundle
      runAfter:
        - validate
      taskRef:
        # TODO: The bundle image build needs to generate a Dockerfile first
        # from the source using opm commands. It's a security risk to allow
        # user specified Dockerfiles as additional malicious steps could be
        # inserted and be near-impossible to guard against.
        #
        # Alternatively, should we instead validate that opm generates the same
        # output as the user submitted Dockerfile? The advantage to this is
        # explicit Dockerfiles that don't need to be committed back to SCM by
        # this pipeline. It's also more opaque to the user which could lead to
        # better usability.
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: &bundleImage "$(params.registry)/$(context.pipelineRun.namespace)/$(tasks.validate.results.package_name):$(tasks.validate.results.bundle_version)"
        - name: CONTEXT
          value: "$(params.bundle_path)"
        # TODO TLS verification disabled for demo purposes
        - &buildahNoTlsVerify
          name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: pipeline
          subPath: src

    - &generateIndex
      name: generate-index-4-5
      runAfter:
        - build-bundle
      taskRef:
        name: generate-index
      params:
        - name: bundle_image
          value: *bundleImage
      when:
        - input: $(tasks.validate.results.supports_ocp_4_5)
          operator: in
          values: ["true"]
      workspaces:
        - name: output
          workspace: pipeline
          subPath: index-4.5

    - &buildIndex
      name: build-index-4-5
      runAfter:
        - generate-index-4-5
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.registry)/$(context.pipelineRun.namespace)/$(tasks.validate.results.package_name)-test-index-4-5:$(tasks.validate.results.bundle_version)"
        - name: CONTEXT
          value: "index-4.5"
        - <<: *buildahNoTlsVerify
      workspaces:
        - name: source
          workspace: pipeline

    - <<: *generateIndex
      name: generate-index-4-6
      when:
        - input: $(tasks.validate.results.supports_ocp_4_6)
          operator: in
          values: ["true"]
      workspaces:
        - name: output
          workspace: pipeline
          subPath: index-4.6

    - <<: *buildIndex
      name: build-index-4-6
      runAfter:
        - generate-index-4-6
      params:
        - name: IMAGE
          value: "$(params.registry)/$(context.pipelineRun.namespace)/$(tasks.validate.results.package_name)-test-index-4-6:$(tasks.validate.results.bundle_version)"
        - name: CONTEXT
          value: "index-4.6"
        - <<: *buildahNoTlsVerify

    - <<: *generateIndex
      name: generate-index-4-7
      when:
        - input: $(tasks.validate.results.supports_ocp_4_7)
          operator: in
          values: ["true"]
      workspaces:
        - name: output
          workspace: pipeline
          subPath: index-4.7

    - <<: *buildIndex
      name: build-index-4-7
      runAfter:
        - generate-index-4-7
      params:
        - name: IMAGE
          value: "$(params.registry)/$(context.pipelineRun.namespace)/$(tasks.validate.results.package_name)-test-index-4-7:$(tasks.validate.results.bundle_version)"
        - name: CONTEXT
          value: "index-4.7"
        - <<: *buildahNoTlsVerify

    - <<: *generateIndex
      name: generate-index-4-8
      when:
        - input: $(tasks.validate.results.supports_ocp_4_8)
          operator: in
          values: ["true"]
      workspaces:
        - name: output
          workspace: pipeline
          subPath: index-4.8

    - <<: *buildIndex
      name: build-index-4-8
      runAfter:
        - generate-index-4-8
      params:
        - name: IMAGE
          value: "$(params.registry)/$(context.pipelineRun.namespace)/$(tasks.validate.results.package_name)-test-index-4-8:$(tasks.validate.results.bundle_version)"
        - name: CONTEXT
          value: "index-4.8"
        - <<: *buildahNoTlsVerify
