---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: operator-cert-authorize
spec:
  params:
    - name: git_base_revision
    - name: github_username
  results:
    - name: bundle_path
  workspaces:
    - name: source
  steps:
    - name: verify-one-operator-bundle
      image: quay.io/amisstea/operator-pipeline-tools:latest
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        set -xe
        BUNDLE=$(git --no-pager diff --name-only HEAD $(params.git_base_revision) \
          | grep -oP 'community-operators/.+?/.+?/' | sort | uniq)
        if [[ $(echo $BUNDLE | wc -l) -ne 1 ]]; then
          echo "Exactly one Operator Bundle per submission is required"
          exit 1
        fi
        echo -n $BUNDLE | tee $(results.bundle_path.path)
    - name: verify-username
      image: quay.io/amisstea/operator-pipeline-tools:latest
      script: |
        #! /usr/bin/env bash
        set -xe
        cat << EOF
        This is a dummy authorization step but it should probably
        lookup the certification project and ensure the submitting user
        is allowed to modify this operator package.
        For demo purposes, $(params.github_username) is authorized!
        EOF
