---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-index
spec:
  params:
    - name: bundle_image
  workspaces:
    - name: output
  steps:
    - name: generate
      image: quay.io/amisstea/operator-pipeline-tools:latest
      workingDir: $(workspaces.output.path)
      script: |
        #! /usr/bin/env bash
        set -xe

        # TODO should --from-index be specified?
        # --permissive is used to overcome errors about the missing bundles
        # this one replaces.
        opm index add \
          --bundles $(params.bundle_image) \
          --container-tool none \
          --out-dockerfile Dockerfile \
          --generate \
          --skip-tls \
          --permissive

        ls -alhR
