---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sleep
spec:
  params:
    - name: time
  steps:
    - name: sleep
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        sleep $(params.time)
