---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: operator-cert-test
spec:
  params:
    - name: package_name
    - name: junit_xml_path
    - name: junit_html_path
    - name: namespace # TODO
      default: ""
    - name: kubeconfig # TODO
      default: ""
  workspaces:
    - name: results
  results:
    - name: state
  steps:
    - name: run-preflight-tests
      # TODO use an image with all the test suites and tools installed
      image: quay.io/amisstea/operator-pipeline-tools:latest
      script: |
        #! /usr/bin/env bash
        set -xe

        # TODO Replace all this with operator tests
        pytest --junitxml "$(workspaces.results.path)/$(params.junit_xml_path)" \
               --html "$(workspaces.results.path)/$(params.junit_html_path)" \
               --self-contained-html \
               $TESTS_HOME

        # Provide a github friendly overall state
        if [[ "$?" -eq "0" ]]; then
          STATE="success"
        else
          STATE="failure"
        fi
        echo -n $STATE > $(results.state.path)
